/// Exact likelihood of pure AR(1) error models — the regression test for the
/// fix recorded as "Local modifications" 10 in third_party/ctsa/PROVENANCE.md.
///
/// Until that fix, ctsa's AS 154 likelihood gave the first observation of an
/// AR(1) error process (ip == 1 && iq == 0 once the seasonal polynomials are
/// multiplied out: ARIMA(1,d,0) with no seasonal AR/MA, any differencing,
/// mean, drift or regressors) variance σ² instead of σ²/(1 − φ²). That moved
/// the optimum, σ² and the log-likelihood.
///
/// Two independent oracles:
///
/// * **Closed forms** at the parameters tseries returned, for every case that
///   reaches the branch: the exact AR(1) log-likelihood and σ² = S/T, and the
///   pure-AR forecast and its standard error from ψ-weights. The forecast is
///   recomputed by ctsa at the returned parameters and agrees to 1e-8
///   relative; the reported log-likelihood and σ² agree at rounding level
///   (since "Local modifications" 13 they are evaluated at the estimate).
/// * **statsmodels' optimum** (`fixtures/ar1_reference.dart`, generated by
///   `tool/ar1_likelihood_reference.py`): the fit must be at least as good
///   (log-likelihood within 1e-4), its ARMA coefficients within 1e-4 and σ²
///   within a factor 1 ± 1e-4 — for the branch AND for neighbouring forms
///   (seasonal AR, MA(1), (0,1,1), AR(2), …) that must not reach it.
///
/// Log-likelihoods are compared as reported: ctsa's ln(2·3.14159) offset was
/// fixed (PROVENANCE.md, "Local modifications" 14).
library;

import 'dart:math' as math;

import 'package:test/test.dart';
import 'package:tseries/tseries.dart';

import 'fixtures/ar1_reference.dart';

ArimaOrder _orderOf(Ar1ReferenceCase c) => ArimaOrder(
  p: c.order[0],
  d: c.order[1],
  q: c.order[2],
  seasonalP: c.seasonal[0],
  seasonalD: c.seasonal[1],
  seasonalQ: c.seasonal[2],
  seasonalPeriod: c.seasonal[3],
);

/// Coefficients of δ(B) = (1 − B)^d (1 − B^s)^D, δ[0] = 1.
List<double> _deltaPoly(ArimaOrder o) {
  var poly = <double>[1];
  List<double> times(List<double> a, int lag) {
    final out = List<double>.filled(a.length + lag, 0);
    for (var i = 0; i < a.length; i++) {
      out[i] += a[i];
      out[i + lag] -= a[i];
    }
    return out;
  }

  for (var i = 0; i < o.d; i++) {
    poly = times(poly, 1);
  }
  for (var i = 0; i < o.seasonalD; i++) {
    poly = times(poly, o.seasonalPeriod);
  }
  return poly;
}

/// One record per fit: the public fields the checks need, whichever path.
typedef _Fit = ({
  String path,
  List<double> arma, // statsmodels order: ar, ma, sar, sma (tseries signs)
  double? intercept,
  Map<String, double?> beta,
  double sigma2,
  double? logLik,
  List<double> forecast,
  List<double> se,
  int retval,
});

const _h = 10;

List<_Fit> _fits(Ar1ReferenceCase c) {
  final order = _orderOf(c);
  final h = c.exog.isEmpty ? _h : 0;
  final out = <_Fit>[];
  for (final m in [SarimaxMethod.cssMle, SarimaxMethod.mle]) {
    final f = fitSarimax(
      c.y,
      c.exog,
      order: order,
      method: m,
      includeMean: c.includeMean,
      includeDrift: c.includeDrift,
      horizon: h,
    );
    out.add((
      path: 'fitSarimax(${m.name})',
      arma: [...f.ar, ...f.ma, ...f.seasonalAr, ...f.seasonalMa],
      intercept: f.intercept,
      beta: {for (final r in f.regressors) r.name: r.coefficient},
      sigma2: f.sigma2,
      logLik: f.logLikelihood,
      forecast: f.forecast,
      se: f.standardErrors,
      retval: f.retval,
    ));
  }
  // fitSarima estimates a mean exactly when nothing is differenced and has no
  // regressors, so it is the same model only in that configuration.
  final nd = order.d + order.seasonalD;
  if (c.exog.isEmpty && !c.includeDrift && c.includeMean == (nd == 0)) {
    final f = fitSarima(c.y, order: order, horizon: h);
    out.add((
      path: 'fitSarima',
      arma: [...f.ar, ...f.ma, ...f.seasonalAr, ...f.seasonalMa],
      intercept: nd == 0 ? f.mean : null,
      beta: const {},
      sigma2: f.sigma2,
      logLik: f.logLikelihood,
      forecast: f.forecast,
      se: f.standardErrors,
      retval: f.retval,
    ));
  }
  return out;
}

/// u_t = y_t − (intercept + regressors + drift·t), at the fitted values.
List<double> _deregressed(Ar1ReferenceCase c, _Fit f) => [
  for (var i = 0; i < c.y.length; i++)
    c.y[i] -
        (f.intercept ?? 0) -
        [
          for (final e in c.exog.entries) (f.beta[e.key] ?? 0) * e.value[i],
        ].fold<double>(0, (a, v) => a + v) -
        (c.includeDrift ? f.beta[sarimaxDriftColumn]! * (i + 1) : 0),
];

/// S, T and the exact AR(1) log-likelihood (σ² profiled, exact π) of the
/// series AS 154 filters, w = δ(B)·u, at the fit's parameters.
({double s, int t, double exact}) _exactAr1(Ar1ReferenceCase c, _Fit f) {
  final phi = f.arma.single;
  final delta = _deltaPoly(_orderOf(c));
  final u = _deregressed(c, f);
  final w = [
    for (var t = delta.length - 1; t < u.length; t++)
      [
        for (var j = 0; j < delta.length; j++) delta[j] * u[t - j],
      ].fold<double>(0, (a, v) => a + v),
  ];
  final e = [
    math.sqrt(1 - phi * phi) * w.first,
    for (var t = 1; t < w.length; t++) w[t] - phi * w[t - 1],
  ];
  final s = e.fold<double>(0, (a, v) => a + v * v);
  final t = w.length;
  final exact =
      -t / 2 * (math.log(2 * math.pi) + math.log(s / t) + 1) +
      0.5 * math.log(1 - phi * phi);
  return (s: s, t: t, exact: exact);
}

void main() {
  for (final c in ar1ReferenceCases) {
    group(c.name, () {
      final fits = _fits(c);
      final names = [
        for (final n in c.names)
          if (n.startsWith('ar.') || n.startsWith('ma.')) n,
      ];

      for (final f in fits) {
        test('${f.path}: at statsmodels\' optimum', () {
          expect(f.retval, 1, reason: 'probable success');
          final ll = f.logLik!;
          expect(ll, greaterThanOrEqualTo(c.llf - 1e-4));
          for (var i = 0; i < names.length; i++) {
            // statsmodels' MA polynomial is 1 + θB, tseries' 1 − θB.
            final sign = names[i].startsWith('ma.') ? -1 : 1;
            expect(
              f.arma[i],
              closeTo(sign * c.param(names[i]), 1e-4),
              reason: names[i],
            );
          }
          expect(f.sigma2 / c.scale, closeTo(1, 1e-4));
        });

        if (!c.inBranch) continue;

        test('${f.path}: exact AR(1) likelihood and σ² in closed form', () {
          final (:s, :t, :exact) = _exactAr1(c, f);
          expect(t, c.t);
          final ll = f.logLik!;
          // Both are evaluated at the returned estimate (PROVENANCE.md, Local
          // modifications 13), so they agree with the closed form at rounding
          // level. Until that fix ctsa reported them from the last objective
          // evaluation inside its finite-difference Hessian -- a point a step
          // away from the estimate, which one depending on the compiler: up to
          // 3.4e-5 off in ll and 2.3e-5 relative in σ² with MSVC, so these
          // checks had to allow 1e-4. Before Local modifications 10 the gap
          // here was up to 132.
          expect(ll, closeTo(exact, 1e-10 * math.max(1, exact.abs())));
          expect(f.sigma2, closeTo(s / t, 1e-12 * s / t));
        });

        if (f.forecast.isEmpty) continue;

        test('${f.path}: forecast and standard error in closed form', () {
          final phi = f.arma.single;
          final o = _orderOf(c);
          final delta = _deltaPoly(o);
          // a(B) = (1 − φB)·δ(B) = 1 − Σ a_j B^j.
          final full = List<double>.filled(delta.length + 1, 0);
          for (var j = 0; j < delta.length; j++) {
            full[j] += delta[j];
            full[j + 1] -= phi * delta[j];
          }
          final a = [for (var j = 1; j < full.length; j++) -full[j]];
          final u = _deregressed(c, f);
          final n = u.length;
          final ext = [...u];
          for (var k = 0; k < _h; k++) {
            var v = 0.0;
            for (var j = 0; j < a.length; j++) {
              v += a[j] * ext[ext.length - 1 - j];
            }
            ext.add(v);
          }
          // ctsa scales the forecast MSE by S/T at the returned parameters.
          final (:s, :t, exact: _) = _exactAr1(c, f);
          final sigma2 = s / t;
          final psi = <double>[1];
          for (var k = 1; k < _h; k++) {
            var v = 0.0;
            for (var j = 1; j <= math.min(k, a.length); j++) {
              v += a[j - 1] * psi[k - j];
            }
            psi.add(v);
          }
          var cum = 0.0;
          for (var k = 0; k < _h; k++) {
            cum += psi[k] * psi[k];
            final level =
                ext[n + k] +
                (f.intercept ?? 0) +
                (c.includeDrift
                    ? f.beta[sarimaxDriftColumn]! * (n + k + 1)
                    : 0);
            expect(
              f.forecast[k],
              closeTo(level, 1e-8 * math.max(1, level.abs())),
              reason: 'forecast h=${k + 1}',
            );
            final se = math.sqrt(sigma2 * cum);
            expect(f.se[k], closeTo(se, 1e-8 * se), reason: 'SE h=${k + 1}');
          }
        });
      }
    });
  }
}
