/// Golden-value validation of the SARIMAX path against statsmodels.
///
/// Reference: statsmodels `SARIMAX(simple_differencing=False, trend='n')` —
/// regression with (seasonal) ARIMA errors, exact likelihood — with standard
/// errors from `cov_type='approx'` (numerical Hessian). The numbers and the
/// versions that produced them live in `fixtures/sarimax_reference.dart`,
/// generated by `tool/sarimax_reference.py`.
///
/// Observed agreement when these tolerances were set (2026-10-04): coefficients
/// ≤ 1.4e-5 abs, log-likelihood ≤ 7.0e-5, forecasts ≤ 2.1e-5 abs, forecast SEs
/// ≤ 2.4e-5 rel, coefficient SEs ≤ 2.8e-5 rel, sigma2 ≤ 4.7e-5 rel. The
/// reference itself moves by up to 1.1e-5 in its coefficients when re-polished
/// by a second optimiser, so the tolerances below leave an order of magnitude
/// of headroom over that noise floor rather than pinning the observed gap.
///
/// SIGN: ctsa's MA polynomial is 1 − θB, statsmodels' is 1 + θB, so tseries's
/// MA estimates are the negated statsmodels values.
library;

import 'package:test/test.dart';
import 'package:tseries/tseries.dart';

import 'fixtures/sarimax_reference.dart';

const _coefTol = 2e-4;
const _llfTol = 2e-3;
const _forecastTol = 2e-4;
const _relSeTol = 2e-3;

ArimaOrder _orderOf(SarimaxReferenceCase c) => ArimaOrder(
  p: c.order[0],
  d: c.order[1],
  q: c.order[2],
  seasonalP: c.seasonal[0],
  seasonalD: c.seasonal[1],
  seasonalQ: c.seasonal[2],
  seasonalPeriod: c.seasonal[3],
);

SarimaxFitResult _fit(SarimaxReferenceCase c) => fitSarimax(
  c.y,
  c.exog,
  order: _orderOf(c),
  futureExog: c.futureExog,
  horizon: c.horizon,
  includeMean: c.includeMean,
  includeDrift: c.includeDrift,
);

Matcher _relClose(double expected, double rel) =>
    closeTo(expected, expected.abs() * rel);

/// statsmodels names our intercept column `const` and the remaining exog
/// columns x1..xk; map tseries's parameter names onto them.
String _smName(SarimaxReferenceCase c, String tseriesName, List<String> exog) {
  if (tseriesName == 'intercept') return 'const';
  final j = exog.indexOf(tseriesName);
  if (j < 0) return tseriesName; // ar.L1, ma.L1, ma.S.L12, ...
  return 'x${j + 1}';
}

void _goldenGroup(String label, SarimaxReferenceCase c) {
  group(label, () {
    late final SarimaxFitResult fit;
    late final List<String> exogNames;

    setUpAll(() {
      fit = _fit(c);
      exogNames = fit.regressors.map((r) => r.name).toList();
    });

    test('converges (status probableSuccess)', () {
      expect(fit.status, ArimaFitStatus.probableSuccess);
    });

    test('ARMA coefficients match (MA sign flipped)', () {
      final o = _orderOf(c);
      for (var i = 0; i < o.p; i++) {
        expect(fit.ar[i], closeTo(c.param('ar.L${i + 1}'), _coefTol));
      }
      for (var i = 0; i < o.q; i++) {
        expect(fit.ma[i], closeTo(-c.param('ma.L${i + 1}'), _coefTol));
      }
      for (var i = 0; i < o.seasonalP; i++) {
        final lag = (i + 1) * o.seasonalPeriod;
        expect(fit.seasonalAr[i], closeTo(c.param('ar.S.L$lag'), _coefTol));
      }
      for (var i = 0; i < o.seasonalQ; i++) {
        final lag = (i + 1) * o.seasonalPeriod;
        expect(fit.seasonalMa[i], closeTo(-c.param('ma.S.L$lag'), _coefTol));
      }
    });

    test('regression coefficients and intercept match', () {
      for (final r in fit.regressors) {
        expect(r.isUsed, isTrue);
        expect(
          r.coefficient,
          closeTo(c.param(_smName(c, r.name, exogNames)), _coefTol),
          reason: r.name,
        );
      }
      if (c.includeMean) {
        expect(fit.intercept, closeTo(c.param('const'), _coefTol));
      } else {
        expect(fit.intercept, isNull);
      }
    });

    test('sigma2, log-likelihood and AIC match', () {
      expect(fit.sigma2, _relClose(c.param('sigma2'), 1e-3));
      expect(fit.logLikelihood, closeTo(c.llf, _llfTol));
      expect(fit.aic, closeTo(c.aic, 2 * _llfTol));
    });

    test('forecast and forecast standard errors match', () {
      expect(fit.forecast, hasLength(c.horizon));
      for (var i = 0; i < c.horizon; i++) {
        expect(fit.forecast[i], closeTo(c.forecast[i], _forecastTol));
        expect(fit.standardErrors[i], _relClose(c.forecastSe[i], _relSeTol));
      }
    });

    test('coefficient standard errors match the numerical Hessian', () {
      final cov = fit.covariance;
      expect(cov, isNotNull);
      for (final name in cov!.parameters) {
        expect(
          cov.standardError(name),
          _relClose(c.se(_smName(c, name, exogNames)), _relSeTol),
          reason: name,
        );
      }
      for (final r in fit.regressors) {
        expect(r.standardError, cov.standardError(r.name));
      }
      if (c.includeMean) {
        expect(fit.interceptStandardError, cov.standardError('intercept'));
      }
    });

    test('covariance is symmetric', () {
      final rows = fit.covariance!.toRows();
      for (var i = 0; i < rows.length; i++) {
        for (var j = 0; j < i; j++) {
          expect(
            rows[i][j],
            closeTo(rows[j][i], 1e-12 + rows[i][j].abs() * 1e-9),
          );
        }
      }
    });
  });
}

void main() {
  _goldenGroup(
    'ARIMA(1,1,1) errors + 2 regressors (n=144, h=6)',
    sarimaxRefNonSeasonal,
  );
  _goldenGroup(
    'SARIMA(0,1,1)(0,1,1)[12] errors + 1 regressor (n=144, h=12)',
    sarimaxRefSeasonal,
  );
  _goldenGroup(
    'ARMA(1,0,1) errors + intercept + 1 regressor, d = 0 (n=120, h=6)',
    sarimaxRefStationaryWithMean,
  );
  _goldenGroup('ARIMA(0,1,1) with drift (n=100, h=5)', sarimaxRefDrift);
}
