/// White-noise orders (p = q = P = Q = 0): white noise with a mean, the random
/// walk with and without drift, (0,2,0) and the seasonal random walks -- the
/// regression test for "Local modifications" 12 in
/// third_party/ctsa/PROVENANCE.md.
///
/// Until that fix ctsa's AS 182 forecaster (`forkal`) refused these orders and
/// returned without writing anything, so the forecast standard errors were
/// uninitialised heap memory (a different value on every call, sometimes NaN),
/// and for a differenced order the point forecast was whatever the caller's
/// buffer held (0 from Dart). The shim now hands them to `forkal` as the AR(1)
/// model with phi = 0, which is the same model.
///
/// Two oracles:
///
/// * **Closed forms** at the parameters tseries returned: the h-step forecast
///   integrates zero-mean future increments (plus the drift / mean), and its
///   variance is sigma^2 * sum_{j<h} psi_j^2 with psi the weights of
///   1 / ((1 - B)^d (1 - B^s)^D) and sigma^2 = forkal's mean squared one-step
///   residual. Agreement 1e-8 relative.
/// * **statsmodels** (`fixtures/white_noise_reference.dart`, generated by
///   `tool/white_noise_reference.py`), evaluated at the closed-form MLE.
library;

import 'dart:math' as math;

import 'package:test/test.dart';
import 'package:tseries/tseries.dart';

import 'fixtures/white_noise_reference.dart';

const _h = 24;

/// Coefficients of (1 - B)^d (1 - B^s)^D, c[0] = 1.
List<double> _diffPoly(int d, int sD, int s) {
  var c = <double>[1];
  List<double> mul(List<double> a, List<double> b) {
    final r = List<double>.filled(a.length + b.length - 1, 0);
    for (var i = 0; i < a.length; i++) {
      for (var j = 0; j < b.length; j++) {
        r[i + j] += a[i] * b[j];
      }
    }
    return r;
  }

  for (var i = 0; i < d; i++) {
    c = mul(c, const [1, -1]);
  }
  for (var i = 0; i < sD; i++) {
    c = mul(c, [1, ...List<double>.filled(s - 1, 0), -1]);
  }
  return c;
}

/// Applies the differencing polynomial to [y] (output starts at index k).
List<double> _difference(List<double> y, List<double> c) => [
  for (var t = c.length - 1; t < y.length; t++)
    [
      for (var k = 0; k < c.length; k++) c[k] * y[t - k],
    ].reduce((a, b) => a + b),
];

class _Expected {
  _Expected(this.forecast, this.stderr);
  final List<double> forecast;
  final List<double> stderr;
}

/// Closed-form forecast at tseries' own parameters: [level] is the value every
/// future differenced observation is expected to take (the mean for d = D = 0,
/// the drift for a drift column, else 0), [resid] the one-step residuals.
_Expected _closedForm(
  List<double> y,
  List<double> c,
  double level,
  List<double> resid,
) {
  final sigma2 = resid.map((e) => e * e).reduce((a, b) => a + b) / resid.length;
  final ext = [...y];
  final k = c.length - 1;
  for (var h = 0; h < _h; h++) {
    var v = level;
    for (var j = 1; j <= k; j++) {
      v -= c[j] * ext[ext.length - j];
    }
    ext.add(v);
  }
  // psi weights of 1 / c(B).
  final psi = List<double>.filled(_h, 0);
  for (var j = 0; j < _h; j++) {
    var v = j == 0 ? 1.0 : 0.0;
    for (var i = 1; i <= math.min(j, k); i++) {
      v -= c[i] * psi[j - i];
    }
    psi[j] = v;
  }
  var acc = 0.0;
  final se = <double>[];
  for (var j = 0; j < _h; j++) {
    acc += psi[j] * psi[j];
    se.add(math.sqrt(sigma2 * acc));
  }
  return _Expected(ext.sublist(y.length), se);
}

void _expectRel(
  List<double> actual,
  List<double> expected,
  double tol,
  String what,
) {
  expect(actual.length, expected.length, reason: what);
  for (var i = 0; i < actual.length; i++) {
    final scale = math.max(expected[i].abs(), 1e-300);
    expect(
      (actual[i] - expected[i]).abs() / scale,
      lessThanOrEqualTo(tol),
      reason: '$what[$i]: ${actual[i]} vs ${expected[i]}',
    );
  }
}

ArimaOrder _order(WhiteNoiseReferenceCase c) => ArimaOrder(
  p: 0,
  d: c.d,
  q: 0,
  seasonalD: c.seasonalD,
  seasonalPeriod: c.period,
);

void main() {
  for (final MapEntry(key: name, value: c) in whiteNoiseReference.entries) {
    final order = _order(c);
    final poly = _diffPoly(c.d, c.seasonalD, c.period);
    final w = _difference(c.y, poly);

    group(name, () {
      if (!c.includeDrift) {
        for (final method in [ArimaMethod.mle, ArimaMethod.css]) {
          test('fitSarima ${method.name}: forecast and SE vs closed form', () {
            final fit = fitSarima(
              c.y,
              order: order,
              horizon: _h,
              method: method,
            );
            final mean = c.includeMean ? fit.mean : 0.0;
            final resid = [for (final v in w) v - mean];
            final e = _closedForm(c.y, poly, mean, resid);
            _expectRel(fit.forecast, e.forecast, 1e-8, 'forecast');
            _expectRel(fit.standardErrors, e.stderr, 1e-8, 'stderr');
          });
        }

        test('fitSarima: statsmodels reference', () {
          final fit = fitSarima(c.y, order: order, horizon: _h);
          if (c.includeMean) {
            // ctsa optimises the mean numerically; statsmodels' is exact.
            expect(fit.mean, closeTo(c.beta.single, 1e-6));
          }
          // Forecasts: exact for differenced orders (nothing is estimated
          // but sigma^2); within the mean's optimiser error otherwise.
          final fTol = c.includeMean ? 1e-6 : 1e-10;
          for (var i = 0; i < _h; i++) {
            expect(
              fit.forecast[i],
              closeTo(c.forecast[i], fTol),
              reason: 'forecast[$i]',
            );
          }
          _expectRel(
            fit.standardErrors,
            c.stderr,
            c.includeMean ? 1e-6 : 1e-10,
            'stderr',
          );
          // sigma^2 and the log-likelihood are evaluated at the returned
          // estimate (PROVENANCE.md, Local modifications 13). With a mean,
          // ctsa's numerically optimised mean is ~1e-7 off statsmodels' exact
          // one, which moves both only at second order. Until that fix they
          // came from the last objective evaluation inside the
          // finite-difference Hessian, up to ~1e-5 off (tolerances 1e-4/1e-5).
          const llTol = 1e-8;
          expect(
            fit.sigma2 / c.sigma2,
            closeTo(1, c.includeMean ? 1e-10 : 1e-12),
          );
          final m = w.length;
          // Like R, ctsa counts only the n - d - s*D differenced
          // observations; statsmodels' exact-diffuse llf also charges
          // -ln(2*pi)/2 for each of the d + s*D diffuse ones. (No pi offset
          // any more: PROVENANCE.md, Local modifications 14.)
          final id = c.d + c.seasonalD * c.period;
          final diffuse = 0.5 * id * math.log(2 * math.pi);
          expect(fit.logLikelihood! - diffuse, closeTo(c.llf, llTol));
          // And the Gaussian closed form at the closed-form sigma^2.
          expect(
            fit.logLikelihood!,
            closeTo(-0.5 * m * (math.log(2 * math.pi * c.sigma2) + 1), llTol),
          );
        });
      }

      test('fitSarimax (no regressors, drift=${c.includeDrift}): '
          'closed form and statsmodels', () {
        final fit = fitSarimax(
          c.y,
          const {},
          order: order,
          horizon: _h,
          includeMean: c.includeMean,
          includeDrift: c.includeDrift,
        );
        double level;
        if (c.includeDrift) {
          level = fit.regressors.single.coefficient!;
          expect(level, closeTo(c.beta.single, 1e-6));
        } else if (c.includeMean) {
          level = fit.intercept!;
          expect(level, closeTo(c.beta.single, 1e-6));
        } else {
          level = 0;
        }
        final resid = [for (final v in w) v - level];
        final e = _closedForm(c.y, poly, level, resid);
        _expectRel(fit.forecast, e.forecast, 1e-8, 'forecast');
        _expectRel(fit.standardErrors, e.stderr, 1e-8, 'stderr');
        final estimated = c.includeDrift || c.includeMean;
        for (var i = 0; i < _h; i++) {
          expect(
            fit.forecast[i],
            closeTo(c.forecast[i], estimated ? 1e-4 : 1e-10),
            reason: 'statsmodels forecast[$i]',
          );
        }
        _expectRel(
          fit.standardErrors,
          c.stderr,
          estimated ? 1e-6 : 1e-10,
          'statsmodels stderr',
        );
      });
    });
  }

  group('determinism (uninitialised standard errors before the fix)', () {
    test('two identical calls give bit-identical results', () {
      final c = whiteNoiseReference['randomWalk']!;
      for (final order in [
        _order(c),
        const ArimaOrder(p: 0, d: 0, q: 0),
        const ArimaOrder(p: 0, d: 1, q: 0, seasonalD: 1, seasonalPeriod: 12),
      ]) {
        final a = fitSarima(c.y, order: order, horizon: _h);
        // Churn the heap between the calls so stale memory would differ.
        for (var i = 0; i < 20; i++) {
          fitSarima(
            c.y,
            order: const ArimaOrder(p: 1, d: 1, q: 1),
            horizon: 7 + i,
          );
        }
        final b = fitSarima(c.y, order: order, horizon: _h);
        expect(b.forecast, a.forecast, reason: '$order');
        expect(b.standardErrors, a.standardErrors, reason: '$order');
        expect(a.standardErrors.every((v) => v.isFinite && v > 0), isTrue);
      }
    });

    test('random walk forecast is the last observation, h-step SE is '
        'sigma*sqrt(h)', () {
      final c = whiteNoiseReference['randomWalk']!;
      final fit = fitSarima(c.y, order: _order(c), horizon: _h);
      for (var h = 1; h <= _h; h++) {
        expect(fit.forecast[h - 1], c.y.last);
        expect(
          fit.standardErrors[h - 1],
          closeTo(
            fit.standardErrors.first * math.sqrt(h.toDouble()),
            1e-12 * fit.standardErrors.first * h,
          ),
        );
      }
    });

    test('arimaForecast accepts the random walk', () {
      final c = whiteNoiseReference['randomWalk']!;
      final f = arimaForecast(c.y, orders: [_order(c)], horizon: 6);
      expect(f.order, _order(c));
      expect(f.point, everyElement(c.y.last));
    });
  });

  group('inputs ctsa could not handle are refused, not run', () {
    final c = whiteNoiseReference['randomWalk']!;

    test('Box-Jenkins with nothing to estimate', () {
      for (final order in [
        _order(c),
        const ArimaOrder(p: 0, d: 2, q: 0),
        const ArimaOrder(p: 0, d: 0, q: 0, seasonalD: 1, seasonalPeriod: 12),
      ]) {
        expect(
          () => fitSarima(
            c.y,
            order: order,
            horizon: 6,
            method: ArimaMethod.boxJenkins,
          ),
          throwsA(
            isA<ArgumentError>().having(
              (e) => '${e.message}',
              'message',
              contains('nothing to estimate'),
            ),
          ),
          reason: '$order',
        );
      }
    });

    test('Box-Jenkins white noise WITH a mean still fits', () {
      final wn = whiteNoiseReference['whiteNoiseMean']!;
      final fit = fitSarima(
        wn.y,
        order: const ArimaOrder(p: 0, d: 0, q: 0),
        horizon: 3,
        method: ArimaMethod.boxJenkins,
      );
      expect(fit.mean, closeTo(wn.beta.single, 1e-6));
      expect(fit.standardErrors.every((v) => v.isFinite && v > 0), isTrue);
    });

    test(
      'Box-Jenkins with a seasonal lag longer than the differenced series',
      () {
        // 20 points, D = 1 at s = 12: 8 differenced values < lag 12.
        expect(
          () => fitSarima(
            c.y.sublist(0, 20),
            order: const ArimaOrder(
              p: 0,
              d: 0,
              q: 0,
              seasonalP: 1,
              seasonalD: 1,
              seasonalPeriod: 12,
            ),
            method: ArimaMethod.boxJenkins,
          ),
          throwsArgumentError,
        );
      },
    );

    test('SARIMAX CSS with no observation beyond the conditioning lags', () {
      // 15 points, D = 1 at s = 12: 3 differenced values, seasonal AR lag 12.
      for (final method in [SarimaxMethod.cssMle, SarimaxMethod.css]) {
        expect(
          () => fitSarimax(
            c.y.sublist(0, 15),
            const {},
            order: const ArimaOrder(
              p: 0,
              d: 0,
              q: 0,
              seasonalP: 1,
              seasonalD: 1,
              seasonalPeriod: 12,
            ),
            method: method,
          ),
          throwsArgumentError,
          reason: method.name,
        );
      }
    });
  });
}
