// dart format off
// ignore_for_file: type=lint, unused_element, unused_field, camel_case_types

// AUTO GENERATED FILE, DO NOT EDIT.
// 
// Generated by `package:ffigen`.
@ffi.DefaultAsset('package:tseries/ctsa')
library;

import 'dart:ffi' as ffi;
/// Estimated peak bytes of ctsa's exact-likelihood state for an order -- the
/// quantity every fixed-order entry point compares with TSERIES_MAX_STATE_BYTES.
/// `with_forecast` adds the AS 182 forecast state (which also grows with
/// d + s*D). Pure arithmetic in 64-bit; never allocates. Returns LLONG_MAX for a
/// configuration too large to even estimate. Negative inputs are treated as 0.
@ffi.Native<ffi.LongLong Function(ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int )>()
external int tseries_model_state_bytes(int p,
int d,
int q,
int s,
int P,
int D,
int Q,
int with_forecast,
);

/// Smoke check: exercises the vendored ctsa (arima_init/arima_free) and returns
/// 42 on success, a negative value on failure. Used only to validate that the
/// native build + link + FFI lookup pipeline works end to end.
@ffi.Native<ffi.Int Function()>()
external int tseries_smoke();

/// ---------------------------------------------------------------------------
/// Fixed-order (Seasonal) ARIMA fit + optional forecast.
/// 
/// For a purely non-seasonal ARIMA(p,d,q) pass s = 0 and P = D = Q = 0.
/// 
/// The caller owns every out buffer. Required lengths:
/// out_phi    : p        (AR coeffs)          NULL allowed iff p == 0
/// out_theta  : q        (MA coeffs)          NULL allowed iff q == 0
/// out_bigphi : P        (seasonal AR)        NULL allowed iff P == 0
/// out_bigtheta: Q       (seasonal MA)        NULL allowed iff Q == 0
/// out_diag   : 4        -> {mean, sigma2, loglik, aic}  (required, non-NULL)
/// out_forecast: horizon (>=0)                NULL allowed iff horizon == 0
/// out_stderr : horizon                       NULL allowed iff horizon == 0
/// (standard errors = sqrt of ctsa's per-step MSE)
/// out_retval : 1        -> ctsa's own fit status (required, non-NULL)
/// 
/// method: 0 = MLE (default), 1 = CSS, 2 = Box-Jenkins.
/// 
/// out_retval receives a TSERIES_RETVAL_* code. It is written as soon as ctsa
/// returns -- BEFORE this shim applies any of its own validation -- so the caller
/// always sees the true ctsa status even when the fit is then rejected as
/// non-finite. It is TSERIES_RETVAL_NOT_RUN if an argument check failed and ctsa
/// was never invoked. NOTE: the shim does not reject any status; interpreting
/// them is the caller's job.
/// 
/// out_diag[2] (loglik) and out_diag[3] (aic) are NaN whenever they are not
/// trustworthy, rather than a plausible-looking number:
/// * aic    is real only for method == MLE with retval == SUCCESS.
/// * loglik is real only for method MLE/CSS with retval == SUCCESS.
/// * Box-Jenkins assigns neither; CSS assigns no aic; and on retval 10/12 ctsa
/// returns before the MLE step, leaving a CSS log-likelihood (and an AIC
/// derived from it) that is not comparable with an MLE fit's.
/// sarima_init leaves those two fields uninitialised, so outside the cases above
/// they are malloc garbage -- this shim therefore never reads them there. mean
/// and sigma2 are always real on TSERIES_OK.
/// 
/// Returns TSERIES_OK, or a negative TSERIES_ERR_* code. On any error the model
/// is fully freed and no partial results should be trusted (but out_retval, if
/// ctsa ran, is still meaningful). TSERIES_ERR_TOO_LARGE is returned, before
/// ctsa is called, when the order's exact-likelihood state would exceed
/// TSERIES_MAX_STATE_BYTES (e.g. a seasonal MA term at s = 288).
/// TSERIES_ERR_BAD_SIZE is returned, before ctsa is called, when the series is
/// too short; on top of the general floor n > d + s*D + p + q + P + Q + 1, with
/// Nd = n - d - s*D the differenced length:
/// * MLE/CSS: Nd <= p + s*P (ctsa's CSS step has no residual left and reads
/// uninitialised memory -- results differ run to run);
/// * Box-Jenkins: p + s*P > Nd or q + s*Q > Nd (out-of-bounds reads), and for
/// a seasonal model (P + Q > 0) Nd <= (P + Q + 1)*s + 1 (uninitialised
/// seasonal autocovariances).
/// PROVENANCE.md, Local modifications 12 and 15.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Double> , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Int> )>()
external int tseries_sarima_fit(ffi.Pointer<ffi.Double> series,
int n,
int p,
int d,
int q,
int s,
int P,
int D,
int Q,
int method,
int horizon,
ffi.Pointer<ffi.Double> out_phi,
ffi.Pointer<ffi.Double> out_theta,
ffi.Pointer<ffi.Double> out_bigphi,
ffi.Pointer<ffi.Double> out_bigtheta,
ffi.Pointer<ffi.Double> out_diag,
ffi.Pointer<ffi.Double> out_forecast,
ffi.Pointer<ffi.Double> out_stderr,
ffi.Pointer<ffi.Int> out_retval,
);

/// ---------------------------------------------------------------------------
/// Regression with (seasonal) ARIMA errors -- SARIMAX -- fit + optional forecast:
/// 
/// y_t = [mu] + sum_j beta_j * x_{j,t} + u_t,   u_t ~ SARIMA(p,d,q)(P,D,Q)[s]
/// 
/// Built on ctsa's sarimax_init/exec/predict/free -- deliberately NOT on ctsa's
/// (since removed) sarimax_wrapper (left `idrift` uninitialised when drift was off,
/// so its predict read garbage) nor auto_arima with xreg (upstream issue #8). The
/// regressors are differenced together with y (d and D), exactly as ctsa does.
/// 
/// Inputs:
/// series      : n                         the observed series
/// xreg        : n*r, COLUMN-major         xreg[j*n + i]; NULL iff r == 0
/// future_xreg : horizon*r, COLUMN-major   future_xreg[j*horizon + i];
/// NULL iff r == 0 or horizon == 0
/// p,d,q,s,P,D,Q : the error model (s = 0 and P = D = Q = 0 for non-seasonal)
/// method      : TSERIES_SARIMAX_METHOD_*  (mapped onto ctsa's numbering)
/// include_mean: 1 = estimate an intercept mu. Only meaningful when
/// d + D == 0; ignored (no intercept) otherwise, as in ctsa.
/// exog_policy : TSERIES_EXOG_POLICY_*
/// 
/// Outputs (caller-owned):
/// out_phi/out_theta/out_bigphi/out_bigtheta : p/q/P/Q, NULL allowed iff 0.
/// MA terms in ctsa's convention, 1 - theta*B (opposite sign to R and
/// statsmodels), exactly as tseries_sarima_fit reports them.
/// out_beta          : r, NULL allowed iff r == 0. NaN for a dropped column.
/// out_column_status : r, NULL allowed iff r == 0. TSERIES_EXOG_* per column.
/// Written on TSERIES_OK and on TSERIES_ERR_EXOG_DEFECT.
/// out_diag          : 4 -> {mean, sigma2, loglik, aic} (required)
/// out_vcov          : k*k row-major, NULL allowed (then not computed), with
/// k = p + q + P + Q + m + r and m = 1 iff an intercept is estimated.
/// Parameter order: phi, theta, PHI, THETA, [mu], beta_0..beta_{r-1};
/// signs follow the reported coefficients. It is the inverse of ctsa's
/// finite-difference Hessian of the (profile) log-likelihood at the
/// optimum. Rows/columns of a dropped regressor are NaN; the whole matrix
/// is NaN whenever it is not trustworthy (see below).
/// out_forecast/out_stderr : horizon, NULL allowed iff horizon == 0
/// out_retval        : 1 (required) -- ctsa's own status, verbatim, as in
/// tseries_sarima_fit (TSERIES_RETVAL_NOT_RUN if ctsa
/// never ran).
/// out_bad_column    : 1 (required) -- index of the first defective regressor
/// column, or -1. Meaningful on TSERIES_ERR_EXOG_DEFECT and
/// on TSERIES_ERR_NON_FINITE (-1 then means "the series").
/// 
/// Trust gates (the same discipline as tseries_sarima_fit):
/// * loglik: real only for retval == SUCCESS and method CSS_MLE / MLE (an
/// exact log-likelihood) or CSS (a CSS log-likelihood); NaN otherwise.
/// * aic:    real only for retval == SUCCESS and method CSS_MLE / MLE. ctsa
/// never assigns it for CSS; on retval 4/10/12/15 under CSS_MLE ctsa returns
/// BEFORE the MLE step with CSS-only estimates.
/// * vcov:   real only for retval == SUCCESS, method CSS_MLE / MLE, and a
/// finite matrix with a strictly positive diagonal. ctsa's CSS-path Hessian
/// is scaled by a wrongly double-differenced length, so it is never
/// reported.
/// * sigma2 <= 0 -> TSERIES_ERR_DEGENERATE (zero forecast uncertainty).
/// * ctsa retval 7 means its regression step never ran at all (every
/// coefficient is still zero); it is reported as
/// TSERIES_ERR_NATIVE_COLLINEAR, never as a fit.
/// 
/// Guards applied BEFORE ctsa is called (each would otherwise reach an exit(),
/// a NaN fit, or an unchecked multi-GB malloc inside ctsa):
/// * every value of series, xreg and future_xreg finite and within
/// +/-TSERIES_MAX_ABS_VALUE; so is every differenced value (differencing
/// can overflow finite input);
/// * regressor screening (TSERIES_EXOG_* above), under exog_policy;
/// * residual degrees of freedom >= TSERIES_MIN_RESIDUAL_DOF;
/// * with seasonal differencing (D > 0) and regressors in use, d * (used
/// regressors) <= n - d - s*D (TSERIES_ERR_BAD_SIZE otherwise): ctsa's
/// regression set-up writes past a heap buffer beyond that;
/// * exact-likelihood state <= TSERIES_MAX_STATE_BYTES;
/// * method is one of TSERIES_SARIMAX_METHOD_* (ctsa would exit(-1)).
/// 
/// Returns TSERIES_OK or a negative TSERIES_ERR_* code.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Double> , ffi.Int , ffi.Pointer<ffi.Double> , ffi.Int , ffi.Pointer<ffi.Double> , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Int , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Int> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Double> , ffi.Pointer<ffi.Int> , ffi.Pointer<ffi.Int> )>()
external int tseries_sarimax_fit(ffi.Pointer<ffi.Double> series,
int n,
ffi.Pointer<ffi.Double> xreg,
int r,
ffi.Pointer<ffi.Double> future_xreg,
int horizon,
int p,
int d,
int q,
int s,
int P,
int D,
int Q,
int method,
int include_mean,
int exog_policy,
ffi.Pointer<ffi.Double> out_phi,
ffi.Pointer<ffi.Double> out_theta,
ffi.Pointer<ffi.Double> out_bigphi,
ffi.Pointer<ffi.Double> out_bigtheta,
ffi.Pointer<ffi.Double> out_beta,
ffi.Pointer<ffi.Int> out_column_status,
ffi.Pointer<ffi.Double> out_diag,
ffi.Pointer<ffi.Double> out_vcov,
ffi.Pointer<ffi.Double> out_forecast,
ffi.Pointer<ffi.Double> out_stderr,
ffi.Pointer<ffi.Int> out_retval,
ffi.Pointer<ffi.Int> out_bad_column,
);


const int TSERIES_OK = 0;


const int TSERIES_ERR_NULL_ARG = -1;


const int TSERIES_ERR_BAD_SIZE = -2;


const int TSERIES_ERR_BAD_PARAM = -3;


const int TSERIES_ERR_INIT_FAILED = -4;


const int TSERIES_ERR_NON_FINITE = -5;


const int TSERIES_ERR_DEGENERATE = -6;


const int TSERIES_ERR_TOO_LARGE = -7;


const int TSERIES_ERR_EXOG_DEFECT = -8;


const int TSERIES_ERR_NATIVE_COLLINEAR = -9;


const int TSERIES_MAX_STATE_BYTES = 67108864;


const int TSERIES_MIN_RESIDUAL_DOF = 2;


const double TSERIES_EXOG_TOL_ZERO = 1e-12;


const double TSERIES_EXOG_TOL_COLLINEAR = 1e-8;


const double TSERIES_MAX_ABS_VALUE = 1e+150;


const int TSERIES_EXOG_USED = 0;


const int TSERIES_EXOG_ALL_ZERO = 1;


const int TSERIES_EXOG_CONSTANT_AFTER_DIFF = 2;


const int TSERIES_EXOG_COLLINEAR_INTERCEPT = 3;


const int TSERIES_EXOG_COLLINEAR = 4;


const int TSERIES_EXOG_POLICY_STRICT = 0;


const int TSERIES_EXOG_POLICY_DROP = 1;


const int TSERIES_SARIMAX_METHOD_CSS_MLE = 0;


const int TSERIES_SARIMAX_METHOD_MLE = 1;


const int TSERIES_SARIMAX_METHOD_CSS = 2;


const int TSERIES_METHOD_MLE = 0;


const int TSERIES_METHOD_CSS = 1;


const int TSERIES_METHOD_BOX_JENKINS = 2;


const int TSERIES_RETVAL_NOT_RUN = 0;


const int TSERIES_RETVAL_SUCCESS = 1;


const int TSERIES_RETVAL_MAX_ITER = 4;


const int TSERIES_RETVAL_COLLINEAR_EXOG = 7;


const int TSERIES_RETVAL_NONSTATIONARY_AR = 10;


const int TSERIES_RETVAL_NONSTATIONARY_SAR = 12;


const int TSERIES_RETVAL_NON_FINITE = 15;

