#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Vladislav Zyuzko
"""Reference values for tseries' clean-room replacements of ctsa's LGPL units.

Writes test/fixtures/cleanroom_reference.txt, consumed by
tool/cleanroom_accuracy.c (see that file for how to build and run it).

Each line is `<kind> <args...> <reference>` with every number printed by
repr() (shortest round-trip form), so the C harness reads them back exactly.

  erfinv  x            scipy.special.erfinv(x)
  erfcinv c            scipy.special.erfcinv(c)
  betainv alpha a b    scipy.special.betaincinv(a, b, alpha)  (x: I_x(a,b) = alpha)
  ibeta   x a b        scipy.special.betainc(a, b, x)          (diagnostic for ctsa's ibeta)
  tinv    p df         scipy.stats.t.ppf(p, df)
  brent   fid lo hi    analytic argmin of test function `fid` on [lo, hi]
  lls     M N cond A(row-major, M*N) b(M) x(N)   (cond = 2-norm condition of A)
                       numpy.linalg.lstsq(A, b) -- exercises minfit() through
                       ctsa's lls_svd2()

Usage (from packages/tseries):  python tool/cleanroom_reference.py
Tested with scipy 1.18.0 / numpy 2.5.1 / Python 3.12.
"""

import math
import pathlib

import numpy as np
import scipy
from scipy import special, stats

OUT = pathlib.Path(__file__).resolve().parent.parent / "test" / "fixtures" / "cleanroom_reference.txt"


def main() -> None:
    lines = [
        "# Generated by tool/cleanroom_reference.py -- do not edit by hand.",
        f"# scipy {scipy.__version__}, numpy {np.__version__}",
    ]

    # --- erfinv: symmetric grid incl. tiny arguments and both tails ----------
    xs = set()
    for v in [1e-300, 1e-100, 1e-20, 1e-10, 1e-5, 1e-3, 0.01, 0.1, 0.2, 0.3, 0.4,
              0.4999999, 0.5, 0.5000001, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99, 0.999,
              1 - 1e-6, 1 - 1e-9, 1 - 1e-12, 1 - 1e-15, 1 - 2**-53]:
        xs.add(v)
        xs.add(-v)
    for v in np.linspace(-0.999, 0.999, 61):
        xs.add(float(v))
    for x in sorted(xs):
        lines.append(f"erfinv {x!r} {float(special.erfinv(x))!r}")

    # --- erfcinv: (0, 2) incl. deep upper tail and the reflected lower one ---
    cs = set()
    for v in [1e-300, 1e-200, 1e-100, 1e-50, 1e-20, 1e-12, 1e-8, 1e-5, 1e-3,
              0.01, 0.05, 0.1, 0.3, 0.4999999, 0.5, 0.5000001, 0.7, 0.9, 1.0,
              1.1, 1.3, 1.5, 1.7, 1.9, 1.99, 2 - 1e-6, 2 - 1e-10]:
        cs.add(v)
    for v in np.linspace(0.001, 1.999, 41):
        cs.add(float(v))
    for c in sorted(cs):
        lines.append(f"erfcinv {c!r} {float(special.erfcinv(c))!r}")

    # --- betainv / ibeta: shapes seen by tinv/finv and generic ones ----------
    alphas = [1e-12, 1e-8, 1e-5, 1e-3, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5,
              0.75, 0.9, 0.95, 0.975, 0.99, 0.999, 1 - 1e-6]
    shapes = [(a, b) for a in (0.5, 1.0, 2.5, 10.0, 50.0, 500.0)
              for b in (0.5, 1.0, 3.0, 20.0)]
    # tinv(p, df) calls betainv(2*min(p,1-p), df/2, 1/2);
    # finv(p, n, d) calls betainv(p, n/2, d/2).
    shapes += [(df / 2.0, 0.5) for df in (1, 2, 3, 5, 7, 12, 30, 100, 999)]
    shapes += [(0.5, 5.0), (1.5, 6.0), (5.0, 50.0)]
    for a, b in shapes:
        for alpha in alphas:
            x = float(special.betaincinv(a, b, alpha))
            if not (0.0 < x < 1.0):
                continue  # outside double range: nothing meaningful to compare
            lines.append(f"betainv {alpha!r} {a!r} {b!r} {x!r}")
            lines.append(f"ibeta {x!r} {a!r} {b!r} {alpha!r}")

    # --- tinv end to end (the SARIMAX regress() path) -------------------------
    for df in (1, 2, 3, 4, 5, 8, 10, 20, 30, 50, 100, 250, 500, 1000):
        for p in (0.0005, 0.005, 0.025, 0.05, 0.1, 0.25, 0.4, 0.6, 0.75, 0.9,
                  0.95, 0.975, 0.995, 0.9995):
            lines.append(f"tinv {p!r} {df} {float(stats.t.ppf(p, df))!r}")

    # --- brent_local_min: analytic minimisers (ids match the C harness) ------
    brent = [
        (0, 0.0, 5.0, 2.0),                        # (x-2)^2
        (1, 3.0, 4.0, math.pi),                    # cos(x)
        (2, 0.0, 2.0, 0.5 ** (1.0 / 3.0)),         # x^4 - 2x
        (3, 0.0, 5.0, 1.0),                        # -x exp(-x)
        (4, 0.0, 1.0, 0.3),                        # |x - 0.3|  (non-smooth)
        (5, 0.0, 3.0, math.log(3.0)),              # exp(x) - 3x
        (6, 1.0, 2.0, 1.0),                        # x  (minimum at the end point)
        (7, -1e3, 1e3, 1e-3),                      # (x - 1e-3)^2 on a wide interval
        (8, 0.01, 1.0, math.exp(-1.0)),            # x log(x)
    ]
    for fid, lo, hi, xmin in brent:
        lines.append(f"brent {fid} {lo!r} {hi!r} {xmin!r}")

    # --- minfit via lls_svd2: full-rank least squares (seeded) --------------
    rng = np.random.default_rng(20261005)
    for m, n in [(1, 1), (3, 3), (5, 5), (8, 3), (20, 6), (50, 10), (3, 6),
                 (4, 4), (12, 12)]:
        a = rng.standard_normal((m, n)) * rng.uniform(0.5, 50.0, size=n)
        b = rng.standard_normal(m) * 10.0
        if m == n and m > 1:
            a = a @ a.T  # symmetric positive definite: the shape regress() solves
        x = np.linalg.lstsq(a, b, rcond=None)[0]
        nums = [float(np.linalg.cond(a)), *a.ravel(), *b, *x]
        lines.append(f"lls {m} {n} " + " ".join(repr(float(v)) for v in nums))

    OUT.write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")
    print(f"wrote {len(lines)} lines to {OUT}")


if __name__ == "__main__":
    main()
