#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Vladislav Zyuzko
"""Reference roots for tseries' clean-room `polyroot()` replacement.

Writes test/fixtures/polyroot_reference.txt, consumed by
tool/polyroot_accuracy.c (see that file for how to build and run it).

Line formats (numbers via repr(), so the C harness reads them back exactly):

  poly <tag> <n> <a_0> ... <a_n> <re_1> <im_1> <cond_1> ... <re_n> <im_n> <cond_n>
      p(z) = a_0 + a_1 z + ... + a_n z^n (increasing powers, as ctsa's
      polyroot() takes them); roots from numpy.roots (LAPACK eigenvalues of the
      companion matrix), Newton-polished in 50-digit decimal arithmetic on the
      exact double coefficients when the root is simple (cond < 1e10); cond_k = sum_i |a_i| |z_k|^i / (|z_k| |p'(z_k)|) is
      the relative condition number of root k (inf for a multiple root).

  inv <tag> <q> <ma_1> ... <ma_q> <out_1> ... <out_q>
      ctsa's invertroot(): the MA polynomial 1 + ma_1 z + ... + ma_q z^q with
      every root inside the unit circle reflected to 1/conj(z); out_k are the
      coefficients of the reflected polynomial (normalised to constant 1).
      Built only from cases whose roots are all well away from |z| = 1.

The AR polynomials used by archeck() are the `poly` lines tagged `ar*`/`sar*`
(a_0 = 1, a_k = -phi_k).

Usage (from packages/tseries):  python tool/polyroot_reference.py
Tested with numpy 2.5.1 / Python 3.12.
"""

import math
import pathlib
from decimal import Decimal, getcontext

import numpy as np

OUT = pathlib.Path(__file__).resolve().parent.parent / "test" / "fixtures" / "polyroot_reference.txt"
RNG = np.random.default_rng(20261005)


def pacf_to_ar(pacf):
    """Durbin-Levinson: partial autocorrelations in (-1, 1) -> stationary AR."""
    phi = []
    for k, r in enumerate(pacf):
        phi = [phi[j] - r * phi[k - 1 - j] for j in range(k)] + [r]
    return np.array(phi)


def from_roots(roots):
    """Real coefficients (increasing powers, a_0 = 1) of prod (1 - z / r)."""
    c = np.array([1.0 + 0j])
    for r in roots:
        c = np.convolve(c, np.array([1.0, -1.0 / r]))
    return np.real(c)


def cond_numbers(a, roots):
    out = []
    pd = np.polynomial.polynomial
    da = pd.polyder(a)
    for z in roots:
        az = abs(z)
        num = sum(abs(ai) * az ** i for i, ai in enumerate(a))
        dp = abs(pd.polyval(z, da))
        out.append(math.inf if dp == 0 or az == 0 else num / (az * dp))
    return out


def refine(a, z, iters=4):
    """Newton-polish root z of the EXACT double coefficients a in 50-digit
    decimal arithmetic, so the reference is the true root of the polynomial
    the C code sees, not numpy's approximation of it (whose error is of the
    same order as the code under test). Only used for simple roots."""
    getcontext().prec = 50
    ca = [Decimal(float(x)) for x in a]
    zr, zi = Decimal(float(z.real)), Decimal(float(z.imag))
    for _ in range(iters):
        pr, pi = ca[-1], Decimal(0)
        dr, di = Decimal(0), Decimal(0)
        for c in reversed(ca[:-1]):
            dr, di = dr * zr - di * zi + pr, dr * zi + di * zr + pi
            pr, pi = pr * zr - pi * zi + c, pr * zi + pi * zr
        den = dr * dr + di * di
        if den == 0:
            break
        zr -= (pr * dr + pi * di) / den
        zi -= (pi * dr - pr * di) / den
    return complex(float(zr), float(zi))


def poly_line(tag, a):
    a = np.asarray(a, dtype=float)
    n = len(a) - 1
    roots = np.roots(a[::-1])  # numpy wants decreasing powers
    conds = cond_numbers(a, roots)
    roots = [refine(a, z) if c < 1e10 else z for z, c in zip(roots, conds)]
    fields = ["poly", tag, str(n)] + [repr(float(x)) for x in a]
    for z, c in zip(roots, conds):
        fields += [repr(float(z.real)), repr(float(z.imag)), repr(float(c))]
    return " ".join(fields)


def inv_line(tag, ma):
    a = np.concatenate(([1.0], ma))
    roots = np.roots(a[::-1])
    refl = np.array([1.0 / np.conj(z) if abs(z) < 1 else z for z in roots])
    out = from_roots(refl)
    fields = ["inv", tag, str(len(ma))] + [repr(float(x)) for x in ma]
    fields += [repr(float(x)) for x in out[1:]]
    return " ".join(fields)


def seasonal(phi, Phi, s):
    """(1 - phi z)(1 - Phi z^s), the AR polynomial of an ARIMA(1,.,0)(1,.,0)_s."""
    a = np.zeros(s + 2)
    a[0] = 1.0
    a[1] = -phi
    a[s] += -Phi
    a[s + 1] += phi * Phi
    return a


def main() -> None:
    lines = [
        "# Generated by tool/polyroot_reference.py -- do not edit by hand.",
        f"# numpy {np.__version__}",
    ]

    # 1. Random stationary AR(p) polynomials (what archeck sees on every fit).
    for p in range(3, 13):
        for k in range(8):
            phi = pacf_to_ar(RNG.uniform(-0.95, 0.95, p))
            lines.append(poly_line(f"ar_p{p}_{k}", np.concatenate(([1.0], -phi))))
    # Non-stationary AR(p): flip one PACF beyond 1 is not a valid PACF, so
    # instead put one real root inside the unit circle.
    for p in range(3, 9):
        for k in range(4):
            roots = list(1.0 / RNG.uniform(0.2, 0.9, 1) * RNG.choice([-1, 1], 1))
            while len(roots) < p:
                if p - len(roots) >= 2 and RNG.uniform() < 0.5:
                    r = RNG.uniform(1.05, 3.0) * np.exp(1j * RNG.uniform(0.1, 3.0))
                    roots += [r, np.conj(r)]
                else:
                    roots.append(RNG.uniform(1.05, 4.0) * RNG.choice([-1, 1]))
            lines.append(poly_line(f"arns_p{p}_{k}", from_roots(roots)))

    # 2. Roots close to the unit circle, both sides (the archeck decision).
    for eps in (1e-2, 1e-3, 1e-5, 1e-7):
        for side in (1.0, -1.0):
            m = 1.0 + side * eps
            for ang in (0.0, 0.3, 1.7, math.pi):
                if ang in (0.0, math.pi):
                    roots = [m * math.cos(ang), 2.5, -1.8]
                else:
                    r = m * np.exp(1j * ang)
                    roots = [r, np.conj(r), 2.0]
                lines.append(poly_line(f"near_{eps:g}_{'out' if side > 0 else 'in'}_{ang:.1f}", from_roots(roots)))

    # 3. Seasonal AR products, up to the 5-minute-CGM daily period.
    for s in (4, 7, 12, 24, 48, 96, 288):
        for phi, Phi in ((0.5, 0.5), (-0.3, 0.9), (0.8, 0.99), (0.2, -0.8), (0.95, 0.3)):
            lines.append(poly_line(f"sar_s{s}_{phi:g}_{Phi:g}", seasonal(phi, Phi, s)))

    # 4. Multiple and clustered roots.
    for r in (1.5, -2.0, 1.0):
        for k in (2, 3, 4):
            lines.append(poly_line(f"mult_{r:g}_x{k}", from_roots([r] * k + [3.0])))
    lines.append(poly_line("cluster", from_roots([1.2, 1.2001, 1.1999, -4.0])))

    # 5. Random coefficients (no structure), moderate and large degree.
    for n in (3, 5, 8, 13, 21, 34, 55, 89):
        for k in range(3):
            lines.append(poly_line(f"rand_n{n}_{k}", RNG.standard_normal(n + 1)))

    # 6. Wide dynamic range of root moduli.
    lines.append(poly_line("range_1e3", from_roots([1e-3, -1e-1, 1.0 + 1e-1, 10.0, -1e3])))
    lines.append(poly_line("range_cplx", from_roots([0.01 * np.exp(1j), 0.01 * np.exp(-1j), 50.0, 400.0 * np.exp(2j), 400.0 * np.exp(-2j)])))

    # invertroot(): MA polynomials (coefficients 1 + ma_1 z + ...).
    for q in range(2, 9):
        for k in range(5):
            roots = []
            while len(roots) < q:
                mod = RNG.choice([RNG.uniform(0.3, 0.9), RNG.uniform(1.1, 3.0)])
                if q - len(roots) >= 2 and RNG.uniform() < 0.5:
                    r = mod * np.exp(1j * RNG.uniform(0.2, 2.9))
                    roots += [r, np.conj(r)]
                else:
                    roots.append(mod * RNG.choice([-1, 1]))
            ma = from_roots(roots)[1:]
            lines.append(inv_line(f"ma_q{q}_{k}", ma))
    for s in (4, 12):
        ma = np.zeros(s)
        ma[s - 1] = -1.4  # 1 - 1.4 z^s: every root inside the unit circle
        lines.append(inv_line(f"sma_s{s}", ma))

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(lines) - 2} cases to {OUT}")


if __name__ == "__main__":
    main()
